Laboratorium3 - Employee/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using Laboratorium3___Employee.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Laboratorium3___Employee.Services;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace Laboratorium3___Employee.Controllers
{
    [Authorize(Roles = "admin")]
    public class DepartmentController : Controller
    {
        private readonly IDepartmentService _departmentService;

        public DepartmentController(IDepartmentService departmentService)
        {
            _departmentService = departmentService;
        }

        [AllowAnonymous]
        public IActionResult Index(int page = 1, int size = 5)
        {
            return View(_departmentService.FindPage(page, size));
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Department model)
        {
            if (ModelState.IsValid) // validation of "Department model"
            {
                _departmentService.Add(model);
                return RedirectToAction("Index");
            }

            return View(model); // show form again - with errors
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var department = _departmentService.FindById(id);
            if (department is null) return NotFound();
            return View(department);
        }

        [HttpPost]
        public IActionResult Update(Department model)
        {
            if (ModelState.IsValid)
            {
                _departmentService.Update(model);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var department = _departmentService.FindById(id);
            if (department is null) return NotFound();
            return View(department);
        }

        [HttpPost]
        public IActionResult Delete(Department model)
        {
            _departmentService.Delete(model.Id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var department = _departmentService.FindById(id);
            if (department is null) return NotFound();
            return View(department);
        }
    }
}

Laboratorium3 - Employee/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using Laboratorium3___Employee.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Laboratorium3___Employee.Services;
using Microsoft.AspNetCore.Authorization;

namespace Laboratorium3___Employee.Controllers
{
    [Authorize(Roles = "admin")]
    public class EmployeeController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly IDepartmentService _departmentService;
        private readonly IPositionService _positionService;

        public EmployeeController(IEmployeeService employeeService, IDepartmentService departmentService, IPositionService positionService)
        {
            _employeeService = employeeService;
            _departmentService = departmentService;
            _positionService = positionService;
        }

        [AllowAnonymous]
        public IActionResult Index(int page = 1, int size = 5)
        {
            var employees = _employeeService.FindPage(page, size);
            foreach (Employee employee in employees.Data)
            {
                employee.Position = _positionService.FindById(employee.PositionId);
                employee.Department = _departmentService.FindById(employee.DepartmentId);
            }
            return View(employees);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new Employee() { PositionList = CreatePositionSelectListItems() });
        }

        [HttpPost]
        public IActionResult Create(Employee model)
        {
            if (ModelState.IsValid) // validation of "Employee model"
            {
                _employeeService.Add(model);
                return RedirectToAction("Index");
            }

            model.PositionList = CreatePositionSelectListItems();
            return View(model); // show form again - with errors
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var employee = _employeeService.FindById(id);
            if (employee is null) return NotFound();
            employee.PositionList = CreatePositionSelectListItems();
            return View(employee);
        }

        [HttpPost]
        public IActionResult Update(Employee model)
        {
            if (ModelState.IsValid)
            {
                _employeeService.Update(model);
                return RedirectToAction("Index");
            }

            model.PositionList = CreatePositionSelectListItems();
            return View(model);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var employee = _employeeService.FindById(id);
            if (employee is null) return NotFound();
            return View(employee);
        }

        [HttpPost]
        public IActionResult Delete(Employee model)
        {
            _employeeService.Delete(model.Id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var employee = _employeeService.FindById(id);
            if (employee is null) return NotFound();
            employee.Position = _positionService.FindById(employee.PositionId);
            employee.Department = _departmentService.FindById(employee.DepartmentId);
            return View(employee);
        }

        private List<SelectListItem> CreatePositionSelectListItems()
        {
            var items = _positionService.FindAll()
                          .Select(e => new SelectListItem()
                          {
                              Text = e.Name,
                              Value = e.Id.ToString()
                          }).ToList();
            return items;
        }
    }
}

Laboratorium3 - Employee/Controllers/PositionController.cs
using Microsoft.AspNetCore.Mvc;
using Laboratorium3___Employee.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Laboratorium3___Employee.Services;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace Laboratorium3___Employee.Controllers
{
    [Authorize(Roles = "admin")]
    public class PositionController : Controller
    {
        private readonly IPositionService _positionService;

        public PositionController(IPositionService positionService)
        {
            _positionService = positionService;
        }

        [AllowAnonymous]
        public IActionResult Index(int page = 1, int size = 5)
        {
            return View(_positionService.FindPage(page, size));
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Position model)
        {
            if (ModelState.IsValid) // validation of "Position model"
            {
                _positionService.Add(model);
                return RedirectToAction("Index");
            }

            return View(model); // show form again - with errors
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var position = _positionService.FindById(id);
            if (position is null) return NotFound();
            return View(position);
        }

        [HttpPost]
        public IActionResult Update(Position model)
        {
            if (ModelState.IsValid)
            {
                _positionService.Update(model);
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var position = _positionService.FindById(id);
            if (position is null) return NotFound();
            return View(position);
        }

        [HttpPost]
        public IActionResult Delete(Position model)
        {
            _positionService.Delete(model.Id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var position = _positionService.FindById(id);
            if (position is null) return NotFound();
            return View(position);
        }
    }
}

Laboratorium3 - Employee/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Laboratorium3___Employee</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/navbar.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/table.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Employee Manager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Position" asp-action="Index">Positions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer">
        <div class="container">
            &copy; 2023 - Mateusz Malinowski - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>